[tool.poetry]
name = "sql2json"
version = "0.1.0"
description = "SQL query to JSON"
authors = ["Francisco Pérez <fsistemas@gmail.com>"]

[tool.poetry.dependencies]
python = "^2.7"
pendulum = "^2.0.5"
SQLAlchemy = "^1.3.12"
click = "^7.0"

[tool.poetry.dev-dependencies]
pytest = "^4.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
